spring:
  application:
    name: foodie-app-auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/foodie_db
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true


server:
  port: 5100
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false